# Generated by Django 5.1.3 on 2025-02-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TatuadorUser',
            fields=[
                ('id_tatuador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('experiencia', models.IntegerField(verbose_name='Años de Experiencia')),
                ('redes_sociales', models.TextField(blank=True, null=True, verbose_name='Redes Sociales')),
                ('portafolio', models.TextField(blank=True, null=True, verbose_name='Portafolio')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('horario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('contraseña', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
        ),
        migrations.CreateModel(
            name='Tatuaje',
            fields=[
                ('id_tatuaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Tatuaje')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('id_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tatuajes', to='myapp.categoria', verbose_name='Categoría')),
                ('id_tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tatuajes', to='myapp.tatuadoruser', verbose_name='Tatuador')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('id_reseña', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(verbose_name='Calificación')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('id_tatuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_recibidas', to='myapp.tatuadoruser', verbose_name='Tatuador')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_creadas', to='myapp.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
